import type { Hole, Plating, Point } from "./parseExcellon";

const fmt = (value: number): string => value.toFixed(4);

const platingComment = (plating: Plating): string | undefined => {
  if (plating === "PTH")
    return "; #@! TA.AperFunction,Plated,PTH,ComponentDrill";
  if (plating === "NPTH")
    return "; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill";
  return undefined;
};

interface SizeTool {
  readonly diameter: number;
  readonly plating: Plating;
  readonly circles: Point[];
  readonly slots: (readonly Point[])[];
}

/**
 * Render holes back into an absolute-metric decimal Excellon file (`FMAT,2`,
 * route-format slots). Holes are bucketed into tools by their nominal size —
 * a circle's diameter or a slot's width — so a file may carry several `T<n>C…`
 * defs (e.g. a pocket bucket holding 1.1mm and 1.2mm holes milled by one cornmill).
 * The tool diameters here are the holes' **true** sizes; the *chosen machining
 * tool* is encoded in the filename, not the file.
 *
 * Written directly rather than via FlatCAM (whose `export_excellon` is broken in
 * this build), and intentionally round-trips through `parseExcellon`.
 */
export const renderExcellon = (holes: readonly Hole[]): string => {
  const bySize = new Map<string, SizeTool>();
  for (const hole of holes) {
    const diameter = hole.kind === "circle" ? hole.diameter : hole.width;
    const key = fmt(diameter);
    let tool = bySize.get(key);
    if (!tool) {
      tool = { diameter, plating: hole.plating, circles: [], slots: [] };
      bySize.set(key, tool);
    }
    if (hole.kind === "circle") {
      tool.circles.push({ x: hole.x, y: hole.y });
    } else {
      tool.slots.push(hole.path);
    }
  }

  const tools = [...bySize.values()].sort((a, b) => a.diameter - b.diameter);

  const header = [
    "M48",
    ";DRILL file generated by flatmaxx (categorized drills)",
    ";FORMAT={-:-/ absolute / metric / decimal}",
    "FMAT,2",
    "METRIC",
  ];
  tools.forEach((tool, index) => {
    const comment = platingComment(tool.plating);
    if (comment) header.push(comment);
    header.push(`T${index + 1}C${fmt(tool.diameter)}`);
  });

  const body: string[] = ["%", "G90", "G05"];
  tools.forEach((tool, index) => {
    body.push(`T${index + 1}`);
    for (const p of tool.circles) {
      body.push(`X${fmt(p.x)}Y${fmt(p.y)}`);
    }
    for (const path of tool.slots) {
      if (path.length < 2) continue;
      const [start, ...rest] = path;
      body.push(`G00X${fmt(start!.x)}Y${fmt(start!.y)}`);
      body.push("M15");
      for (const p of rest) {
        body.push(`G01X${fmt(p.x)}Y${fmt(p.y)}`);
      }
      body.push("M16");
      body.push("G05");
    }
  });

  return [...header, ...body, "T0", "M30", ""].join("\n");
};
