import { Array, Match, Option, Order, pipe, Record, Result } from "effect";
import { COORD_DECIMALS, MIN_ROUTE_POINTS } from "./constants";
import type { Hole, Plating, Point, SizeTool } from "./types";

const fmt = (value: number): string => value.toFixed(COORD_DECIMALS);

const platingComment = (plating: Plating): Option.Option<string> =>
  pipe(
    Match.value(plating),
    Match.when("PTH", () =>
      Option.some("; #@! TA.AperFunction,Plated,PTH,ComponentDrill"),
    ),
    Match.when("NPTH", () =>
      Option.some("; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill"),
    ),
    Match.orElse(() => Option.none()),
  );

const sizeOf = (hole: Hole): number =>
  hole.kind === "circle" ? hole.diameter : hole.width;

const toSizeTool = (group: readonly Hole[]): SizeTool => {
  const [circles, slots] = Array.partition(group, (hole) =>
    hole.kind === "circle"
      ? Result.fail({ x: hole.x, y: hole.y })
      : Result.succeed(hole.path),
  );
  return {
    diameter: sizeOf(group[0]!),
    plating: group[0]!.plating,
    circles,
    slots,
  };
};

const bucketBySize = (holes: readonly Hole[]): readonly SizeTool[] =>
  pipe(
    Array.groupBy(holes, (hole) => fmt(sizeOf(hole))),
    Record.values,
    Array.map(toSizeTool),
    Array.sort(Order.mapInput(Order.Number, (t: SizeTool) => t.diameter)),
  );

const headerSection = (tools: readonly SizeTool[]): readonly string[] => [
  "M48",
  ";DRILL file generated by flatmaxx (categorized drills)",
  ";FORMAT={-:-/ absolute / metric / decimal}",
  "FMAT,2",
  "METRIC",
  ...Array.flatMap(tools, (tool, index) => [
    ...Array.getSomes([platingComment(tool.plating)]),
    `T${index + 1}C${fmt(tool.diameter)}`,
  ]),
];

const slotLines = (path: readonly Point[]): readonly string[] =>
  Match.value(path.length).pipe(
    Match.when(
      (n) => n < MIN_ROUTE_POINTS,
      () => [],
    ),
    Match.orElse(() => {
      const [start, ...rest] = path;
      return [
        `G00X${fmt(start!.x)}Y${fmt(start!.y)}`,
        "M15",
        ...Array.map(rest, (p) => `G01X${fmt(p.x)}Y${fmt(p.y)}`),
        "M16",
        "G05",
      ];
    }),
  );

const toolBody = (tool: SizeTool, index: number): readonly string[] => [
  `T${index + 1}`,
  ...Array.map(tool.circles, (p) => `X${fmt(p.x)}Y${fmt(p.y)}`),
  ...Array.flatMap(tool.slots, slotLines),
];

const bodySection = (tools: readonly SizeTool[]): readonly string[] => [
  "%",
  "G90",
  "G05",
  ...Array.flatMap(tools, toolBody),
];

export const renderExcellon = (holes: readonly Hole[]): string => {
  const tools = bucketBySize(holes);
  return pipe(
    [...headerSection(tools), ...bodySection(tools), "T0", "M30", ""],
    Array.join("\n"),
  );
};
