import { expect, test } from "bun:test";
import {
  assembleCarveraGcode,
  extractToolpathBody,
  type ToolSection,
} from "./ncGcode";

const SAMPLE = `(G-code generated by FlatCAM)
(Units: MM)
G21
G90
G94

G01 F120.00
G00 Z2.0000

M03 S15000.0
G01 F120.00
G00 X5.5 Y5.4
G01 Z-0.0500
G01 X6.0 Y6.0
G00 Z2.0000
M05
G00 Z2.0000
G00 Z15.00
G00 X0.0 Y0.0
`;

test("extracts only the motion body between M03 and M05", () => {
  const body = extractToolpathBody(SAMPLE);
  expect(body[0]).toBe("G01 F120.00");
  expect(body).toContain("G01 Z-0.0500");
  expect(body.at(-1)).toBe("G00 Z2.0000");
  expect(body).not.toContain("M03 S15000.0");
  expect(body).not.toContain("M05");
  expect(body).not.toContain("G00 Z15.00");
});

test("assembles sections with clean Carvera toolchanges + single spindle stop", () => {
  const sections: ToolSection[] = [
    {
      toolNumber: 1,
      label: "0.8mm mill",
      spindleSpeed: 15000,
      travelZ: 2,
      body: ["G00 X1 Y1", "G01 Z-0.0750", "G01 X2 Y2", "G00 Z2.0000"],
    },
    {
      toolNumber: 2,
      label: "0.198mm V-bit",
      spindleSpeed: 15000,
      travelZ: 2,
      body: ["G00 X3 Y3", "G01 Z-0.0500", "G01 X4 Y4", "G00 Z2.0000"],
    },
  ];
  const out = assembleCarveraGcode(sections, {
    seamZ: 15,
    endZ: 15,
    headerComments: ["flatmaxx front"],
  });

  // forces safe modal state, never G20
  expect(out).toContain("G21");
  expect(out).toContain("G90");
  expect(out).toContain("G94");
  expect(out).not.toMatch(/^G20\b/m);

  // one-line toolchanges (no T\nM6 bug), with operator message
  expect(out).toContain("M6 T1");
  expect(out).toContain("(MSG, Change to 0.8mm mill)");
  expect(out).toContain("M6 T2");
  expect(out).toContain("(MSG, Change to 0.198mm V-bit)");

  // spindle restarted after each toolchange, stopped once at the very end
  expect(out.match(/^M3 S15000$/gm)).toHaveLength(2);
  expect(out.trimEnd().endsWith("M30")).toBe(true);

  // seam retract before each toolchange
  expect(out).toContain("G00 Z15.0000");
  // tool bodies present and ordered (mill before V-bit)
  expect(out.indexOf("Z-0.0750")).toBeLessThan(out.indexOf("Z-0.0500"));
});

test("body extraction returns empty when no spindle-on is present", () => {
  expect(extractToolpathBody("G21\nG90\n(no motion)\n")).toEqual([]);
});
